# Generated by Django 4.2.7 on 2023-12-07 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=1)),
                ('birthplace', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=1)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1homepage.driver')),
            ],
        ),
    ]
