# Generated by Django 4.2.7 on 2023-12-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1homepage', '0002_driver_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifying',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
