# Generated by Django 4.2.7 on 2023-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1homepage', '0004_alter_qualifying_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifying',
            name='gp',
            field=models.CharField(default='バーレーンGPサウジアラビアGPオーストラリアGPアゼルバイジャンGPマイアミGPモナコGPスペインGPカナダGPオーストリアイギリスGPハンガリーGPベルギーGPオランダGPイタリアGPシンガポールGP日本GPアメリカGPメキシコシティGPサンパウロGPラスベガスGPアブダビGP', max_length=100),
        ),
    ]
