# Generated by Django 4.2.7 on 2023-12-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1homepage', '0005_alter_qualifying_gp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifying',
            name='gp',
            field=models.CharField(choices=[('default', 'バーレーンGP'), ('サウジアラビアGP', 'サウジアラビアGP'), ('オーストラリアGP', 'オーストラリアGP'), ('アゼルバイジャンGP', 'アゼルバイジャンGP'), ('マイアミGP', 'マイアミGP'), ('モナコGP', 'モナコGP'), ('スペインGP', 'スペインGP'), ('カナダGP', 'カナダGP'), ('オーストリアGP', 'オーストリアGP'), ('イギリスGP', 'イギリスGP'), ('ハンガリーGP', 'ハンガリーGP'), ('ベルギーGP', 'ベルギーGP'), ('オランダGP', 'オランダGP'), ('イタリアGP', 'イタリアGP'), ('シンガポールGP', 'シンガポールGP'), ('日本GP', '日本GP'), ('アメリカGP', 'アメリカGP'), ('メキシコシティGP', 'メキシコシティGP'), ('シンガポールGP', 'シンガポールGP'), ('日本GP', '日本GP'), ('アメリカGP', 'アメリカGP'), ('メキシコシティGP', 'メキシコシティGP'), ('サンパウロGP', 'サンパウロGP'), ('ラスベガスGP', 'ラスベガスGP'), ('アブダビGP', 'アブダビGP')], default='default', max_length=100),
        ),
    ]
