# Generated by Django 4.2.7 on 2023-12-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1homepage', '0006_alter_qualifying_gp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifying',
            name='gp',
            field=models.CharField(max_length=100),
        ),
    ]
