# Generated by Django 4.2.7 on 2023-12-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1homepage', '0007_alter_qualifying_gp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2023)),
                ('gp', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=1)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1homepage.driver')),
            ],
        ),
    ]
