# Generated by Django 4.2.7 on 2023-12-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1homepage', '0009_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='driver_images/'),
        ),
    ]
